### ISSUE TITLE
Adding fields to the sitewide contact form

### ISSUE THREAD

**Issue by JessicaFrank** [CCALI/drupal7-a2j#15] opened 2015-12-04 16:22 UTC
So I was able to add categories of issues that people can send us emails about via the sitewide contact form. However, I need to add fields to the form --

What browser they are using; What OS; GI number (with an explanation of how to find that) -- maybe others

This page says to use a Block to add additional text, but I can't figure it out from the Blocks Admin page.
![image](https://cloud.githubusercontent.com/assets/7662028/11594662/de124f14-9a70-11e5-91d2-dc1359f8adc7.png)

**Comment by emasters** [comment] 2015-12-17 14:48
@JessicaFrank The better approach to this is to use webforms instead of the contact form. Using webform provides a lot more flexibility to create and gather the info you need. It even has conditional branching! For a good tutorial see https://www.youtube.com/watch?v=PRci_xRDTE0
I noticed that you've started a couple already so I'd suggest using them instead of the sitewide contact form.

**Comment by emasters** [comment] 2015-12-17 15:21
This is a duplicate of #11

**Closed by emasters** 2015-12-17 15:21 UTC
Labels: duplicate
